// <auto-generated />
namespace PraktyczneKursy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Elmah : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Elmah));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281037182_Elmah"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
